version: '3'
services:
    openeo-r-validator-data:
        build: 
            context: .
            dockerfile: DOCKERFILE
        image: openeo-r-vdata-importer:0.1
        container_name: openeo-r-validator-importer
        volumes:
            - openeo-r-download:/var/openeo/tmp/
            - openeo-r-workspace:/var/openeo/
        restart: "no"
        environment:
            - COPERNICUS_USER=
            - COPERNICUS_PWD=
            - DELETE_TMP_FILES=false
            - DATA_ITALY=true
            - DATA_SWITZERLAND=true
            - DATA_UGANDA=true
            - DATA_ISLAND=true
            - DATA_VENEZUELA=true
            - DATA_NETHERLANDS=true
        command: ["R", "-q", "--no-save", "-f /opt/dockerfiles/importer.R"]
volumes:
    openeo-r-download:
    openeo-r-workspace: